version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - mynet

  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 5000
      BASE_URL: "/api/employees"
      MONGO_LOCAL_URI: mongodb://mongodb:27017/employees
    ports:
      - "5000:5000"
    networks:
      - mynet
    depends_on:
      - mongodb
volumes:
  mongodb-data:


networks:
  mynet:
    driver: bridge
